name: fdas

services:
  postgres:
    image: postgres:18.1-alpine
    container_name: postgres_db_18
    restart: always
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      PGDATA: /var/lib/postgresql/data

    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka-native:4.1.1
    container_name: kafka_broker
    restart: always
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
        - ./tmp/kafka_data:/kafka/data
