/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as EditorDemoRouteImport } from './routes/editor-demo'
import { Route as CodeEditorDemoRouteImport } from './routes/code-editor-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories/index'
import { Route as RepositoriesOwnerRepoRouteImport } from './routes/repositories/$owner/$repo'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorDemoRoute = EditorDemoRouteImport.update({
  id: '/editor-demo',
  path: '/editor-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeEditorDemoRoute = CodeEditorDemoRouteImport.update({
  id: '/code-editor-demo',
  path: '/code-editor-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesOwnerRepoRoute = RepositoriesOwnerRepoRouteImport.update({
  id: '/repositories/$owner/$repo',
  path: '/repositories/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code-editor-demo': typeof CodeEditorDemoRoute
  '/editor-demo': typeof EditorDemoRoute
  '/search': typeof SearchRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code-editor-demo': typeof CodeEditorDemoRoute
  '/editor-demo': typeof EditorDemoRoute
  '/search': typeof SearchRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/code-editor-demo': typeof CodeEditorDemoRoute
  '/editor-demo': typeof EditorDemoRoute
  '/search': typeof SearchRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/code-editor-demo'
    | '/editor-demo'
    | '/search'
    | '/repositories'
    | '/repositories/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/code-editor-demo'
    | '/editor-demo'
    | '/search'
    | '/repositories'
    | '/repositories/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/code-editor-demo'
    | '/editor-demo'
    | '/search'
    | '/repositories/'
    | '/repositories/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeEditorDemoRoute: typeof CodeEditorDemoRoute
  EditorDemoRoute: typeof EditorDemoRoute
  SearchRoute: typeof SearchRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
  RepositoriesOwnerRepoRoute: typeof RepositoriesOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor-demo': {
      id: '/editor-demo'
      path: '/editor-demo'
      fullPath: '/editor-demo'
      preLoaderRoute: typeof EditorDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-editor-demo': {
      id: '/code-editor-demo'
      path: '/code-editor-demo'
      fullPath: '/code-editor-demo'
      preLoaderRoute: typeof CodeEditorDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$owner/$repo': {
      id: '/repositories/$owner/$repo'
      path: '/repositories/$owner/$repo'
      fullPath: '/repositories/$owner/$repo'
      preLoaderRoute: typeof RepositoriesOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeEditorDemoRoute: CodeEditorDemoRoute,
  EditorDemoRoute: EditorDemoRoute,
  SearchRoute: SearchRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
  RepositoriesOwnerRepoRoute: RepositoriesOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
