/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories/index'
import { Route as RepositoriesOwnerRepoRouteImport } from './routes/repositories/$owner/$repo'
import { Route as ChatAgentIdThreadIdRouteImport } from './routes/chat/$agentId/$threadId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesOwnerRepoRoute = RepositoriesOwnerRepoRouteImport.update({
  id: '/repositories/$owner/$repo',
  path: '/repositories/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatAgentIdThreadIdRoute = ChatAgentIdThreadIdRouteImport.update({
  id: '/chat/$agentId/$threadId',
  path: '/chat/$agentId/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/chat/$agentId/$threadId': typeof ChatAgentIdThreadIdRoute
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/chat/$agentId/$threadId': typeof ChatAgentIdThreadIdRoute
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/chat/$agentId/$threadId': typeof ChatAgentIdThreadIdRoute
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/repositories'
    | '/chat/$agentId/$threadId'
    | '/repositories/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/repositories'
    | '/chat/$agentId/$threadId'
    | '/repositories/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/repositories/'
    | '/chat/$agentId/$threadId'
    | '/repositories/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
  ChatAgentIdThreadIdRoute: typeof ChatAgentIdThreadIdRoute
  RepositoriesOwnerRepoRoute: typeof RepositoriesOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$owner/$repo': {
      id: '/repositories/$owner/$repo'
      path: '/repositories/$owner/$repo'
      fullPath: '/repositories/$owner/$repo'
      preLoaderRoute: typeof RepositoriesOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$agentId/$threadId': {
      id: '/chat/$agentId/$threadId'
      path: '/chat/$agentId/$threadId'
      fullPath: '/chat/$agentId/$threadId'
      preLoaderRoute: typeof ChatAgentIdThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
  ChatAgentIdThreadIdRoute: ChatAgentIdThreadIdRoute,
  RepositoriesOwnerRepoRoute: RepositoriesOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
